### PR TITLE
commit something to start ci

### PR DESCRIPTION
**Pull request by jjsjann123**
<details>
  <summary><b>Before submitting</b></summary>

- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contributor guideline](https://github.com/Lightning-AI/pytorch-lightning/blob/main/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to update the docs?
- [ ] Did you write any new necessary tests?

</details>

## What does this PR do?

Fixes # (issue).

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by crcrpar** [comment]
would this repo somehow happen to disallow [`--allow-empty`](https://git-scm.com/docs/git-commit/2.31.0#Documentation/git-commit.txt---allow-empty)?

**Comment by jjsjann123** [comment]
> would this repo somehow happen to disallow [`--allow-empty`](https://git-scm.com/docs/git-commit/2.31.0#Documentation/git-commit.txt---allow-empty)?

Not sure about that. I didn't see github prompt a merge request when I push an empty branch to the repo.
Felt it's easier to push another one, rather than going through github GUI via virtual desktop....

**Comment by t-vi** [comment]
Hi @jjsjann123  What's up with this?

**Comment by jjsjann123** [comment]
sorry, this is meant for a CI smoke test. I'll close it.

**Pull request closed without merging**
