### PR TITLE
add ProxyTag and static memory location tagging for cudagraphs

### PR DESCRIPTION
**Pull request by t-vi**
This is one of the outcomes of the design discussion re #981 .

We add a ProxyTag mechanism (with registration) and introduce STATIC_MEMORY_LOCATION as the first tag.

We then use this tag for knowing the static inputs in the CUDAGraph transform.

### CODE REVIEW

**Review by lantiga — APPROVED** [review]
Looks great.

I'm thinking in terms of composition: how would we handle two different transforms registering the same tag (due to naming collisions)?

Maybe not a problem for now but at least a warning on register_tag if the tag is already registered could be useful for now.

**Comment by t-vi** [comment]
I'll send a follow-up blocking double registration.

**Comment by t-vi** [comment]
Don't know what the CI wants there. :/

**Comment by riccardofelluga** [comment]
I guess I have a question here, what happens if the proxies are changed in some transform before they get a chance to be used? How do we intend to keep track of that?

CC some more people for visibility of this new feature
@IvanYashchuk @mruberry @kshitij12345 @kiya00 @crcrpar

**Comment by mruberry** [comment]
> I guess I have a question here, what happens if the proxies are changed in some transform before they get a chance to be used? How do we intend to keep track of that?
> 
> CC some more people for visibility of this new feature @IvanYashchuk @mruberry @kshitij12345 @kiya00 @crcrpar

Would you file an issue for this so we can track the discussion?

**Pull request merged**
