### PR TITLE
ci: re-build dockers with each commit to `main`

### PR DESCRIPTION
**Pull request by Borda**
# Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/pytorch-lightning/blob/main/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure to update the docs?
- [x] Did you write any new necessary tests?

## What does this PR do?

this would enable some quick updates

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by t-vi** [comment]
Uh, OK, what does that mean for the CI load?

**Comment by Borda** [comment]
> Uh, OK, what does that mean for the CI load?

with #36 we are going back to update only two images, but yes each commit to main would be followed by 1h compilation/install time split into two machines

**Comment by Borda** [comment]
To resolve the actual blocker we need to:
1. land https://github.com/Lightning-AI/pytorch-lightning/pull/19688 and https://github.com/Lightning-AI/pytorch-lightning/pull/19687
2. make new nightly releases of lightning
3. update `litGPT`
4. update pin here

**Comment by t-vi** [comment]
a 1-hour job after each commit sounds like it would put quite a strain on the CI.

**Comment by Borda** [comment]
> a 1-hour job after each commit sounds like it would put quite a strain on the CI.

I think it is fine, regarding you will gain a way to rebuild dockers out of 4h cycle

**Pull request closed without merging**
