### PR TITLE
filter future warning in CI

### PR DESCRIPTION
**Pull request by t-vi**

### CODE REVIEW

**Comment by crcrpar** [comment]
example warning is https://dev.azure.com/Lightning-AI/lightning/_build/results?buildId=211244&view=logs&j=5b0799f7-725e-5b16-9b83-c0a5a25d03f0&t=b8fb81b4-a852-5840-c46b-c8dd0b71557c&l=125

**Comment by crcrpar** [comment]
It doesn't look like the filter isn't effective

**Comment by t-vi** [comment]
Yeah, I'm fixing it, just compiled a new PyTorch

**Comment by t-vi** [comment]
OK, I need to guard the bert run because transformers is also running the deprecated symbol (actually we didn't call it).

**Comment by t-vi** [comment]
Merged as CI fix.

**Pull request merged**
