### PR TITLE
removing test for symbolic values cache running on different devices

### PR DESCRIPTION
**Pull request by jjsjann123**
removes unnecessary devices in tests

### CODE REVIEW

**Comment by jjsjann123** [comment]
follow up for comment https://github.com/Lightning-AI/lightning-thunder/pull/1260#discussion_r1792608435

**Review by tfogal — APPROVED** [review]
thanks

**Comment by jjsjann123** [comment]
tagging @t-vi for a merge stamp.

**Review by lantiga — APPROVED** [review]
Stamped!

**Pull request merged**
