### PR TITLE
Bumps cudnn FE to v1.5.2

### PR DESCRIPTION
**Pull request by vedaanta**
<details>
 
## What does this PR do?
Updates cudnn-fe to 1.5.2

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Review by Borda — APPROVED** [review]

**Comment by Borda** [comment]
running in https://dev.azure.com/Lightning-AI/lightning/_build/results?buildId=206791&view=results

**Comment by t-vi** [comment]
@vedaanta Do you know what  to do about the failures in the nightly check: https://dev.azure.com/Lightning-AI/lightning/_build/results?buildId=206808&view=logs&j=5b0799f7-725e-5b16-9b83-c0a5a25d03f0&t=97651ec4-0b0f-5455-bbb5-3c30427a0a7e  to me, they look somewhat similar to the ones I disabled cudnn tests on 2.4dev until last week.

**Comment by vedaanta** [comment]
> @vedaanta Do you know what to do about the failures in the nightly check: https://dev.azure.com/Lightning-AI/lightning/_build/results?buildId=206808&view=logs&j=5b0799f7-725e-5b16-9b83-c0a5a25d03f0&t=97651ec4-0b0f-5455-bbb5-3c30427a0a7e to me, they look somewhat similar to the ones I disabled cudnn tests on 2.4dev until last week.

Yes, the commit that caused the earlier sdpa failure on pyt main has been merged again.
Thunder CI breaks with 2.5.0a0+git92be340. [LINK](https://dev.azure.com/Lightning-AI/lightning/_build/results?buildId=206808&view=logs&j=5b0799f7-725e-5b16-9b83-c0a5a25d03f0&t=bfc58c43-3926-56c0-cfe2-c80ddf7731a1)
It worked fine with 2.5.0a0+gitb1f486a. [LINK](https://dev.azure.com/Lightning-AI/lightning/_build/results?buildId=206784&view=logs&jobId=5b0799f7-725e-5b16-9b83-c0a5a25d03f0&j=5b0799f7-725e-5b16-9b83-c0a5a25d03f0&t=97651ec4-0b0f-5455-bbb5-3c30427a0a7e)

The suspicious commit between the them is the one that enable cudnn sdpa by default on pyt main. [LINK](https://github.com/pytorch/pytorch/commit/b7e7a4cb01de394af7686ab6feb216a8a5c716bb)

Will take a look and let pyt devs know.

**Comment by t-vi** [comment]
Thank you @vedaanta @Borda

**Pull request merged**
