### PR TITLE
Add lookaside for `torch.autograd.function.Function.apply`

### PR DESCRIPTION
**Pull request by crcrpar**
Fixes https://github.com/Lightning-AI/lightning-thunder/issues/694#issuecomment-2201959134

### CODE REVIEW

**Review by t-vi — APPROVED** [review]
Thank you @crcrpar . At some point we might move the warning into the lookaside, but let's have this now.

**Comment by lantiga** [comment]
Great @crcrpar. Why do we need to `skip_inplace_functionalization`?

**Comment by crcrpar** [comment]
> Great @crcrpar. Why do we need to `skip_inplace_functionalization`?

thank you.
We don't need it. I vaguely remember that I turned it off because the test cases don't use any in-place thus functionalization isn't needed

**Comment by lantiga** [comment]
I would avoid turning defaults off ad-hoc, they will be less likely to break for unforseen interactions.

**Comment by crcrpar** [comment]
100% agreed. opened 712 :)

**Pull request merged**
