### PR TITLE
Add activation checkpointing to the LitGPT benchmark

### PR DESCRIPTION
**Pull request by mpatel31415**
<details>
  <summary><b>Before submitting</b></summary>

- [ ] Was this discussed/approved via a Github issue? 
- [ ] Did you read the [contributor guideline](https://github.com/Lightning-AI/pytorch-lightning/blob/main/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to update the docs?
- [ ] Did you write any new necessary tests?

</details>

## What does this PR do?

It adds changes described [in this issue](https://github.com/Lightning-AI/lightning-thunder/issues/375).
This code works for eager and inductor compilation methods. Next step would be to make it work for Thunder. 

I can add test of this new flag in test_benchmark_litgpt.py however I was not able to run the tests there, so I'm not sure if this is good idea. 

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?

Yes 😀

Fixes https://github.com/Lightning-AI/lightning-thunder/issues/375

### CODE REVIEW

**Review by IvanYashchuk — APPROVED** [review]
Thank you, Martyna!
Making this work in Thunder would take some time but it's good to start measuring the baseline to target with this.

FYI @parthmannan

**Review by carmocca — APPROVED** [review]
LGTM!

**Comment by parthmannan** [comment]
[nit] Can we add an assert that fails if Thunder based compiler is being used with activation checkpointing until we enable the feature in Thunder?
Otherwise looks good! Thanks @mpatel31415

**Review by parthmannan — APPROVED** [review]

**Comment by mpatel31415** [comment]
> [nit] Can we add an assert that fails if Thunder based compiler is being used with activation checkpointing until we enable the feature in Thunder? Otherwise looks good! Thanks @mpatel31415

Sure, I've added it.

**Review by crcrpar — APPROVED** [review]

**Pull request merged**
