### PR TITLE
add helper for `SigInfo` creation in `Function.apply` lookaside

### PR DESCRIPTION
**Pull request by crcrpar**
## What does this PR do?

As per title, add a helper, as we repeat the same thrice in the lookaside

cc @borda

### CODE REVIEW

**Review by IvanYashchuk — APPROVED** [review]
Nice!

**Comment by t-vi** [comment]
This is nice, but wouldn't the real deal be making siginfo optional?
The only thing we don't have is placeholder names for constants, which could just be made up on the fly when doing `.python()`.

**Comment by crcrpar** [comment]
> wouldn't the real deal be making siginfo optional?

If we are to do this, I reckon siginfo should be hidden inside of trace and it should always be created from trace's args, instead of allowing some freedom by making it optional.

**Comment by t-vi** [comment]
> If we are to do this, I reckon siginfo should be hidden inside of trace and it should always be created from trace's args, instead of allowing some freedom by making it optional.

So the siginfo does three things:
- hold names - the proxies in args already have them, the others are actually consts and could just use unused proxies in args with a value equal to the const value,
- hold default args (not used often, but we probably still want this but it could be a dict),
- mark *arg and **kwarg (I'm not sure we support this properly and I don't think it is used, if we want that, it would likely need fixing).

The trouble I have with siginfo that it's most often not used much except for the names and that it can go out of sync, leading to inconsistencies. This is why I'd think using proxies in all arg for the names (might need adjustments, though) and keeping the default arguments elsewhere would let us move to a single source of truth.

**Comment by t-vi** [comment]
That said, this PR strictly improves things, so, yay!

**Review by t-vi — APPROVED** [review]
Thank you @crcrpar  @IvanYashchuk.
I'd like to remove siginfo, but clearly this is better than before.

**Pull request merged**
