### PR TITLE
Enable apex tests

### PR DESCRIPTION
**Pull request by IvanYashchuk**
Fixes https://github.com/Lightning-AI/lightning-thunder/issues/220

### CODE REVIEW

**Review by t-vi — APPROVED** [review]
Thank you @IvanYashchuk @crcrpar

**Comment by IvanYashchuk** [comment]
> would it make sense to pass the kwarg of [`strict`](https://docs.pytest.org/en/stable/how-to/skipping.html#strict-parameter) so that we could get notified by CI?

Yes, I prefer strict xfails usually, but nothing can be done here. It's working locally and I hope it will work in the CI as well.

**Comment by IvanYashchuk** [comment]
Need to fix:
```py
FAILED thunder/tests/test_apex_executor.py::test_apex_cross_entropy_phantom_grad[cuda-float32] - RuntimeError: Comparing

TensorLikePair(
    id=(),
    actual=tensor([[1.5042e-05, 1.3645e-05, 4.9493e-06,  ..., 1.4746e-06, 2.7498e-05,
         1.2589e-06],
        [4.4824e-06, 5.7637e-07, 1.4427e-05,  ..., 3.4280e-05, 2.6549e-05,
         1.9564e-05],
        [9.8489e-06, 2.2216e-05, 1.8847e-05,  ..., 1.0029e-05, 5.4192e-06,
         6.1135e-06],
        ...,
        [7.9177e-06, 1.4364e-05, 9.1391e-06,  ..., 3.2629e-06, 4.4863e-06,
         1.0217e-05],
        [1.4893e-05, 1.6226e-05, 6.0917e-06,  ..., 1.8286e-05, 6.1691e-05,
         2.9350e-05],
        [6.6514e-06, 3.7269e-05, 1.4657e-05,  ..., 1.7162e-05, 5.7013e-06,
         2.1428e-05]], device='cuda:0'),
    expected=tensor([[1.5042e-05, 1.3645e-05, 4.9494e-06,  ..., 1.4746e-06, 2.7498e-05,
         1.2589e-06],
        [4.4824e-06, 5.7637e-07, 1.4427e-05,  ..., 3.4280e-05, 2.6549e-05,
         1.9564e-05],
        [9.8489e-06, 2.2216e-05, 1.8847e-05,  ..., 1.0029e-05, 5.4192e-06,
         6.1135e-06],
        ...,
        [7.9177e-06, 1.4364e-05, 9.1391e-06,  ..., 3.2629e-06, 4.4863e-06,
         1.0217e-05],
        [1.4893e-05, 1.6226e-05, 6.0917e-06,  ..., 1.8286e-05, 6.1691e-05,
         2.9350e-05],
        [6.6514e-06, 3.7269e-05, 1.4657e-05,  ..., 1.7162e-05, 5.7013e-06,
         2.1428e-05]], device='cuda:0', dtype=torch.float64),
    rtol=1.3e-06,
    atol=1e-05,
    equal_nan=False,
    check_device=True,
    check_dtype=False,
    check_layout=True,
    check_stride=False,
)

resulted in the unexpected exception above. If you are a user and see this message during normal operation please file an issue at https://github.com/pytorch/pytorch/issues. If you are a developer and working on the comparison functions, please except the previous error and raise an expressive `ErrorMeta` instead.
FAILED thunder/tests/test_apex_executor.py::test_apex_cross_entropy_phantom_grad[cuda-bfloat16] - torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 198.00 MiB. GPU 0 has a total capacity of 23.69 GiB of which 195.31 MiB is free. Process 373664 has 9.98 GiB memory in use. Process 373670 has 606.00 MiB memory in use. Process 373679 has 574.00 MiB memory in use. Process 373673 has 626.00 MiB memory in use. Process 373667 has 2.68 GiB memory in use. Process 373676 has 944.00 MiB memory in use. Process 373683 has 6.34 GiB memory in use. Process 373687 has 1.18 GiB memory in use. Process 373691 has 616.00 MiB memory in use. Of the allocated memory 5.96 GiB is allocated by PyTorch, and 11.49 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
= 2 failed, 4189 passed, 730 skipped, 86 xfailed, 94 xpassed, 105193 warnings in 570.25s (0:09:30)
```

**Review by t-vi — CHANGES_REQUESTED** [review]
These tests need to either run outside the parallel or reduce their memory use #392 . Could you look into this, please?

**Comment by IvanYashchuk** [comment]
@t-vi, what do you mean by running "outside the parallel"?

**Comment by lantiga** [comment]
@t-vi clarification needed here ☝️

**Comment by t-vi** [comment]
Not sure what I can say beyond the linked #392. These tests use multiple GB of GPU memory leading to OOM when run with the normal tests. If reducing the amount of memory used in the test is not an option, we should move them to test_networks or introduce a flag like I proposed in #219 to run them with no parallelism.

**Comment by t-vi** [comment]
@IvanYashchuk I would propose to close this for now, as it has conflicts and the actual solution is move involved, as in it would likely not be easier to update this than start from scratch. Please reopen if you disagree.

**Pull request closed without merging**
