### PR TITLE
skip DDPTest unless >=2 GPUs

### PR DESCRIPTION
**Pull request by xwang233**
There are some "distributed" test failures, e.g. `thunder.tests.distributed.test_ddp.DDPTest.test_ddp_compile_module` detected in our CI on **single** GPU machines. That test passes correctly on multi-GPU nodes. Since it says it's DDP test, it should be skipped on nodes without enough GPUs.

This PR skips DDPTest unless `torch.cuda.device_count() >= 2`

### CODE REVIEW

**Review by crcrpar — COMMENTED** [review]
your point makes sense but I so far have run some test cases e.g. test_ddp_compile_module as a minimal check in my local environment where only one cuda device is available and it has worked fine.
Would you know whether or not we could forcefully run this test file even if the `skipUnless` cond is not met?

**Comment by xwang233** [comment]
`test_ddp_compile_module` failed in our latest CI environment, with 1 GPU, with the following error message. Would you be interested in fixing the issue instead?

```python
/usr/local/lib/python3.10/dist-packages/torch/testing/_internal/common_distributed.py:541: in wrapper
    self._join_processes(fn)
/usr/local/lib/python3.10/dist-packages/torch/testing/_internal/common_distributed.py:767: in _join_processes
    self._check_return_codes(elapsed_time)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <thunder.tests.distributed.test_ddp.DDPTest testMethod=test_ddp_compile_module>
elapsed_time = 6.109721660614014

    def _check_return_codes(self, elapsed_time) -> None:
        """
        Checks that the return codes of all spawned processes match, and skips
        tests if they returned a return code indicating a skipping condition.
        """
        # If no processes are spawned, there is nothing to check.
        if not self.processes:
            logger.warning("Note: no subprocesses were spawned, test was likely skipped.")
            return
    
        first_process = self.processes[0]
        # first, we check if there are errors in actual processes
        # (via TEST_ERROR_EXIT CODE), and raise an exception for those.
        # the reason we do this is to attempt to raise a more helpful error
        # message than "Process x terminated/timed out"
        # TODO: we should pipe the exception of the failed subprocess here.
        # Currently, the actual exception is displayed as a logging output.
        errored_processes = [
            (i, p)
            for i, p in enumerate(self.processes)
            if p.exitcode == MultiProcessTestCase.TEST_ERROR_EXIT_CODE
        ]
        if errored_processes:
            error = ""
            for i, process in errored_processes:
                # Get error from pipe.
                error_message = self.pid_to_pipe[process.pid].recv()
                error += (
                    f"Process {i} exited with error code {MultiProcessTestCase.TEST_ERROR_EXIT_CODE} "
                    f"and exception:\n{error_message}\n"
                )
    
>           raise RuntimeError(error)
E           RuntimeError: Process 0 exited with error code 10 and exception:
E           Traceback (most recent call last):
E             File "/usr/local/lib/python3.10/dist-packages/torch/testing/_internal/common_distributed.py", line 664, in run_test
E               getattr(self, test_name)()
E             File "/usr/local/lib/python3.10/dist-packages/torch/testing/_internal/common_distributed.py", line 543, in wrapper
E               fn()
E             File "/usr/local/lib/python3.10/dist-packages/torch/testing/_internal/common_utils.py", line 2918, in wrapper
E               method(*args, **kwargs)
E             File "/opt/pytorch/lightning-thunder/thunder/tests/distributed/test_ddp.py", line 84, in test_ddp_compile_module
E               loss = _get_last_loss(fn)
E             File "/opt/pytorch/lightning-thunder/thunder/tests/distributed/test_ddp.py", line 71, in _get_last_loss
E               ddp_model = fn(model)
E             File "/opt/pytorch/lightning-thunder/thunder/tests/distributed/test_ddp.py", line 64, in <lambda>
E               lambda model: ddp(thunder.jit(model)),
E             File "/opt/pytorch/lightning-thunder/thunder/distributed/__init__.py", line 309, in ddp
E               model_new = add_transform(model, transform=transform_from_trace_to_ddp_trace)
E             File "/opt/pytorch/lightning-thunder/thunder/core/transforms.py", line 424, in add_transform
E               jfn = jit(
E             File "/opt/pytorch/lightning-thunder/thunder/__init__.py", line 819, in jit
E               transform.transform_module(fn_)
E             File "/opt/pytorch/lightning-thunder/thunder/distributed/transforms/ddp_v2.py", line 77, in transform_module
E               tdist.broadcast(model.get_parameter(pn), src=broadcast_from, group=process_group, async_op=False)
E             File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 83, in wrapper
E               return func(*args, **kwargs)
E             File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 2433, in broadcast
E               group_src_rank = get_group_rank(group, src)
E             File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 941, in get_group_rank
E               raise ValueError(f"Global rank {global_rank} is not part of group {group}")
E           ValueError: Global rank True is not part of group <torch.distributed.distributed_c10d.ProcessGroup object at 0x7fdfbcb25db0>
E           
E           To execute this test, run the following from the base repo dir:
E               python test_ddp.py DDPTest.test_ddp_compile_module
E           
E           This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0

/usr/local/lib/python3.10/dist-packages/torch/testing/_internal/common_distributed.py:816: RuntimeError
```

**Comment by crcrpar** [comment]
> Would you be interested in fixing the issue instead?

#983 fixed it locally. I checked it by with and without `CUDA_VISIBLE_DEVICES="0"`

**Comment by t-vi** [comment]
So my interpretation is that #983 supersedes this?

**Review by t-vi — APPROVED** [review]
Thank you @xwang233 @crcrpar

**Comment by t-vi** [comment]
Sorry, wrong button. :(

**Pull request merged**
