### PR TITLE
Add `is_cpu` flag to `fd.define_tensor`

### PR DESCRIPTION
**Pull request by Priya2698**
By default, `is_cpu=False` when defining tensors for `FusionDefinition`. 
This PR sets the `is_cpu` flag based on `x`.

Motivation: `philox_seed/philox_offset` in SDPA are CPU scalar tensors which are incorrectly declared as CUDA tensors. We do not see an error currently because these variables were marked as CPU scalars in the CPP code [here](https://github.com/NVIDIA/Fuser/blob/de1672c653094062d46125ed622d2b781a50aa77/csrc/ops/composite.cpp#L616-L618) (to be removed after this PR). So even though, these tensors were not marked as CPU scalars in `fd.define_tensor`, the tensorviews have the correct device set before runFusion / evaluateFusionOutputs is called.

### CODE REVIEW

**Review by jjsjann123 — APPROVED** [review]
LGTM.

My naive question, the existing code shouldn't be functional, since we would try to access the scalar tensor on gpu device. Do we have any idea on how existing test is passing?

**Comment by Priya2698** [comment]
> LGTM.
> 
> My naive question, the existing code shouldn't be functional, since we would try to access the scalar tensor on gpu device. Do we have any idea on how existing test is passing?

Yes, it is because these variables were marked as CPU scalars in the CPP code [here](https://github.com/NVIDIA/Fuser/blob/de1672c653094062d46125ed622d2b781a50aa77/csrc/ops/composite.cpp#L616-L618). I will remove that following this PR (to avoid breaking Thunder CI). So even though, these tensors were not marked as CPU scalars in `define_tensor`, the tensorviews have the correct device set before `runFusion / evaluateFusionOutputs` is called.

**Comment by jjsjann123** [comment]
> > LGTM.
> > My naive question, the existing code shouldn't be functional, since we would try to access the scalar tensor on gpu device. Do we have any idea on how existing test is passing?
> 
> Yes, it is because these variables were marked as CPU scalars in the CPP code [here](https://github.com/NVIDIA/Fuser/blob/de1672c653094062d46125ed622d2b781a50aa77/csrc/ops/composite.cpp#L616-L618). I will remove that following this PR (to avoid breaking Thunder CI). So even though, these tensors were not marked as CPU scalars in `define_tensor`, the tensorviews have the correct device set before `runFusion / evaluateFusionOutputs` is called.

Now I remembered that you told me this last week already. :face_with_head_bandage: Thanks for putting this here for the record as well.

**Comment by Priya2698** [comment]
> > > LGTM.
> > > My naive question, the existing code shouldn't be functional, since we would try to access the scalar tensor on gpu device. Do we have any idea on how existing test is passing?
> > 
> > 
> > Yes, it is because these variables were marked as CPU scalars in the CPP code [here](https://github.com/NVIDIA/Fuser/blob/de1672c653094062d46125ed622d2b781a50aa77/csrc/ops/composite.cpp#L616-L618). I will remove that following this PR (to avoid breaking Thunder CI). So even though, these tensors were not marked as CPU scalars in `define_tensor`, the tensorviews have the correct device set before `runFusion / evaluateFusionOutputs` is called.
> 
> Now I remembered that you told me this last week already. 🤕 Thanks for putting this here for the record as well.

Good point, updated the PR description for record keeping.

**Review by t-vi — APPROVED** [review]
Thank you @Priya2698 @jjsjann123

**Pull request merged**
