### PR TITLE
restore previous adaptive average pool 2d handling

### PR DESCRIPTION
**Pull request by t-vi**
Fixes: #1178

### CODE REVIEW

**Comment by t-vi** [comment]
So with this, we get
```
FAILED thunder/tests/test_grad.py::test_vjp_correctness_adaptive_avg_pool2d_torch_cuda_thunder.dtypes.float64 - NotImplementedError: VJP for torch.nn.functional.adaptive_avg_pool2d is not implemented
```

**Comment by crcrpar** [comment]
It seems that this approach puts backward only to torchexecutor, not `thunder.core.transforms` namespace, leading to the error. I tried setting CompileData to populate Torch Executor, to let vjp transform see the vjp rule from https://github.com/Lightning-AI/lightning-thunder/blob/9580411e1dcec34ce0226a5a688ed65c32422b8b/thunder/core/transforms.py#L1406 in #1185.
Then I see max_pool_2d failing.

**Comment by crcrpar** [comment]
tried something clumsy in https://github.com/Lightning-AI/lightning-thunder/pull/1185 on top of this PR

**Comment by t-vi** [comment]
thank you @crcrpar

**Review by lantiga — APPROVED** [review]
Stamped!

**Pull request merged**
