### PR TITLE
Revert "cache params/buffers/submodules in ThunderModule (#421)"

### LINKED ISSUE #432: Broken CI tests for distributed
## 🐛 Bug
The following test
`pytest -sv thunder/tests/distributed/test_ddp.py -k test_fsdp_grad_parity_with_without_bucketing_executor_torch_bucketing_block_zero3_fsdp_jit`
fails.
It seems like https://github.com/Lightning-AI/lightning-thunder/pull/421 is the cause.

cc @apaz-cli

### PR DESCRIPTION
**Pull request by t-vi**
Fixes #432 

Thank you @nikitaved and everyone for the analysis

### CODE REVIEW

**Comment by t-vi** [comment]
(Emergency merge for the CI)

**Comment by tfogal** [comment]
FYI @mpatel31415 @parthmannan this perf fix had to be reverted due to a CI issue, you may experience perf regressions until the patch can be revisited.

**Comment by t-vi** [comment]
Yeah, I had hoped to have a proper fix sooner, but it is not clear that it arrives today.

**Comment by tfogal** [comment]
> Yeah, I had hoped to have a proper fix sooner, but it is not clear that it arrives today.

np! Sometimes these things take time, that's understandable.
If you could CC Martyna + Parth on the update to that commit (whenever it happens), we'd very much appreciate it!

**Pull request merged**
