### PR TITLE
`normalize`: stabilize (grad) tests

### PR DESCRIPTION
**Pull request by nikitaved**
As per title. Fixes https://github.com/Lightning-AI/lightning-thunder/issues/835

### CODE REVIEW

**Review by t-vi — APPROVED** [review]
Thank you. That is quite a bit more sophisticated that what I had, let's see if it works. :crossed_fingers:

**Comment by nikitaved** [comment]
Took a couple of iterations to make it pass my high bar of 10k runs of each single test :)

**Comment by t-vi** [comment]
Seems there is some xpass with strict xfail...

**Comment by t-vi** [comment]
The failing test looks like #844 in another shape.

**Pull request merged**
