### PR TITLE
bumps cudnnex to 1.2.1 (PR2485)

### PR DESCRIPTION
**Pull request by vedaanta-nvidia**
## What does this PR do?
Bumps cudnn FE version to 1.2.1

### CODE REVIEW

**Review by Borda — APPROVED** [review]

**Comment by Borda** [comment]
just rerun the GPU test in about an hour when the new dockers are updates :flamingo:

**Review by t-vi — APPROVED** [review]
Thank you @vedaanta-nvidia @Borda

**Comment by wujingyue** [comment]
Great to see the upgrade, Vedaanta! Let me know if you wrote this down somewhere: What does 1.2.1 bring to Thunder? For example, does it fix some disabled tests [here](https://github.com/Lightning-AI/lightning-thunder/blob/483c352839c16042a891625144d3ec0232d54d5a/thunder/tests/test_cudnn_executor.py#L203-L206)?

**Comment by vedaanta-nvidia** [comment]
https://github.com/NVIDIA/cudnn-frontend/releases/tag/v1.2.1
1.2.1 was done to fix the way FE finds cudnn_backend(BE) as compared to torch.

On larger note, there is a push going on right now to publish FE on pypi. This required quite a few changes to FE internally. One such change was the dlopen order of BE libs.
1.2.0 broke with thunder CI. [more info on this slack thread](https://pytorch-lightning.slack.com/archives/C04N128ARJ6/p1710343360218489)
Now with the new order of dlopen in 1.2.1, FE integration seems better.

**Pull request merged**
