### PR TITLE
Bumps cudnn frontend to v1.3.0

### PR DESCRIPTION
**Pull request by vedaanta-nvidia**
<details>
  <summary><b>Before submitting</b></summary>

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/pytorch-lightning/blob/main/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure to update the docs?
- [x] Did you write any new necessary tests?

</details>

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

### CODE REVIEW

**Comment by Borda** [comment]
once the docker images are build and pushed we can rerun CI for GPU
running: https://dev.azure.com/Lightning-AI/lightning/_build/results?buildId=198115&view=logs&j=5590d1c6-4d73-5164-c2d0-7f7286b3996d

**Review by Borda — APPROVED** [review]

**Comment by Borda** [comment]
likely it would need land #155 before...

**Comment by vedaanta-nvidia** [comment]
@t-vi This is ready to go in. Can you please approve? 😄

**Review by t-vi — APPROVED** [review]
Thank you @vedaanta-nvidia @Borda

**Pull request merged**
