### PR TITLE
[nvfuser] don't allow shape only nvfuser region

### PR DESCRIPTION
**Pull request by kshitij12345**
Related: https://github.com/Lightning-AI/lightning-thunder/issues/1251

Microbenchmark
```python
import torch
import torch.utils.benchmark
import thunder

# Seen in HF-Qwen2 Model
# [t6866] = nvFusion4(t6857)
#     # lora_res_12 = prims.reshape(t6857, (1, 4096, 16))  # lora_res_12: "cuda:0 bf16[1, 4096, 16]"
#     # t6866 = prims.reshape(lora_res_12, (4096, 16))  # t6866: "cuda:0 bf16[4096, 16]"

def fn(x):
    x = x.reshape(-1, 4096, 16)
    x = x.reshape(4096, 16)
    return x


x = torch.randn(4096, 16, device="cuda")
jfn = thunder.jit(fn, nv_enable_shape_only_fusion=False)

jfn(x)

timer = torch.utils.benchmark.Timer("jfn(x)", globals={"jfn": jfn, "x": x})

print(timer.blocked_autorange(min_run_time=1))
# print(thunder.last_traces(jfn)[-1])
```

Before PR
```python
<torch.utils.benchmark.utils.common.Measurement object at 0x7305591c54e0>
jfn(x)
  Median: 36.18 us
  3 measurements, 10000 runs per measurement, 1 thread
```

After PR
```python
<torch.utils.benchmark.utils.common.Measurement object at 0x7e533962cc10>
jfn(x)
  Median: 18.95 us
  IQR:    0.02 us (18.93 to 18.96)
  6 measurements, 10000 runs per measurement, 1 thread
```

TODO 
* [x] Add tests!
* [x] Check if CI works fine

### CODE REVIEW

**Review by t-vi — APPROVED** [review]
Seems good, thank you @kshitij12345 .

**Comment by IvanYashchuk** [comment]
The pull request description mentions the `nv_enable_shape_only_fusion` option, but it's not added in the merged commit.

**Comment by kshitij12345** [comment]
> The pull request description mentions the nv_enable_shape_only_fusion option, but it's not added in the merged commit.

Oops, I think I had added for benchmarking but removed it. I think in most scenarios, we won't want a Shape Op only nvFuser region. Do you think adding the option will be useful? Will send a patch accordingly. Thanks for catching this.

**Comment by IvanYashchuk** [comment]
Yes, an option will be useful for ease of experimentation. There could be certain connectivity patterns of fusions allowing shape operations to be copied into other fusions and save on global memory tensors with fusions rematerialization pass as https://github.com/Lightning-AI/lightning-thunder/pull/1371 shows (if only nvfuser linear is enabled (no matmul) memory savings are achieved only if in addition there are shape only fusions in backward).

**Pull request merged**
