### PR TITLE
Preserve tags when swapping proxies

### PR DESCRIPTION
**Pull request by ali-alshaar7**
<details>
  <summary><b>Before submitting</b></summary>

- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contributor guideline](https://github.com/Lightning-AI/pytorch-lightning/blob/main/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to update the docs?
- [ ] Did you write any new necessary tests?

</details>

## What does this PR do?

While testing LitGPT Llama 3 8b, we ran into an issue where one of the kv-cache symbols had its name updated without carrying the `ProxyTag.STATIC_MEMORY_LOCATION` tag. 

This causes `CUDAGraphsTransform` to avoid updating the kv-cache of that layer after each inference step, resulting in bad outputs.

This PR makes cloning a Proxy perform a reference assignment on tags instead of copying.

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by t-vi** [comment]
Hmm. I think I would prefer to fix this at the level of proxy creation.
proxy.replace_name (via proxy.replace) should actually preserve proxy tags, so I'm not entirely sure where the untagged proxies are created...

**Comment by ali-alshaar7** [comment]
> Hmm. I think I would prefer to fix this at the level of proxy creation. proxy.replace_name (via proxy.replace) should actually preserve proxy tags, so I'm not entirely sure where the untagged proxies are created...

So the renaming map is actually created in an interpreter callback. This happens before the tags are added to the inputs. We could pass the proxy renaming map to `unpack_inputs` so that tags being added to one adds it to the other, or make the `tag` `set()` a pointer or something. I think the point is that tagging one proxy should also tag all the others its connected to.

**Comment by ali-alshaar7** [comment]
> Hmm. I think I would prefer to fix this at the level of proxy creation. proxy.replace_name (via proxy.replace) should actually preserve proxy tags, so I'm not entirely sure where the untagged proxies are created...

So the tagging actually happens after the swap map is cerated, and since we are currently copying tag sets, we end up not propagating tagging. 

Simplest fix is make tags a pointer when cloning proxies. I think it makes sense since memory management should be handled by GC, so no memory safety issues. In terms of correctness, do we want tags of a cloned proxy to be different ever? Probably no, but im not sure.

**Review by lantiga — APPROVED** [review]
Great catch!

**Comment by t-vi** [comment]
Thank you for revising the mechanism, great work @ali-alshaar7

**Pull request merged**
