### PR TITLE
docker: compile TE

### LINKED ISSUE #196: [ci] : We should add a CI flow with TransformerEngine installed so that we can run the relevant tests.
We don't have a flow for testing TransformerEngine (TE) executor. 

It would be great to have a CI flow with TE installed to be able to run relevant tests so that we can catch the breakages early. It can also be enabled only before merge or with a github comment.

**NOTE**: TE needs to be built from source at the moment. (@xwang233 knows how to set this up in docker).

cc: @Borda

### PR DESCRIPTION
**Pull request by Borda**
<details>
  <summary><b>Before submitting</b></summary>

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/pytorch-lightning/blob/main/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to update the docs?
- [ ] Did you write any new necessary tests?

</details>

## What does this PR do?

Fixes #196

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?

Make sure you had fun coding 🙃

cc @borda

### CODE REVIEW

**Comment by Borda** [comment]
any hint on how to set the CUDNN path? https://dev.azure.com/Lightning-AI/lightning/_build/results?buildId=199551&view=log[…]c2d0-7f7286b3996d&t=3cfa2d55-62a7-5f49-36ea-726d310411c0&l=204

**Comment by Borda** [comment]
pending on #243

**Comment by IvanYashchuk** [comment]
Should `git+https://github.com/NVIDIA/TransformerEngine.git@stable` be added to the devel.txt requirements?
https://github.com/NVIDIA/TransformerEngine?tab=readme-ov-file#pip

**Comment by Borda** [comment]
> Should `git+https://github.com/NVIDIA/TransformerEngine.git@stable` be added to the devel.txt requirements? [NVIDIA/TransformerEngine#pip](https://github.com/NVIDIA/TransformerEngine?tab=readme-ov-file#pip)

well, in another form, it could be but not be re-installed once it exists
anyway, I still have some difficulty in compiling/installing it

**Comment by kshitij12345** [comment]
I think we should pursue PR this once we have GPU with compute capability 8.9 or above. 
See comment: https://github.com/Lightning-AI/lightning-thunder/issues/196#issuecomment-2077507187

**Comment by lantiga** [comment]
Closing for now, labeled as "later"

**Pull request closed without merging**
